GET https://rocky-harbor-47876.herokuapp.com/api/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYW5zIiwiaWQiOiI2MjMwNTVhMTYzZDQxYTNlZjdmNTRmNzYiLCJpYXQiOjE2NDg0ODAyNTQsImV4cCI6MTY0ODQ4Mzg1NH0.3FCGkhTyHw7ns_A2jZ2ITMBpLmxwjHOyeA6axbU1I40