GET http://localhost:3002/api/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYW5zIiwiaWQiOiI2MjMwNTVhMTYzZDQxYTNlZjdmNTRmNzYiLCJpYXQiOjE2NDczNTg5NDIsImV4cCI6MTY0NzM2MjU0Mn0.3oSU8FBxqWxdVYpUgyA5_ho_MrEWiW9PanCq9Nfzz0c