post http://localhost:3002/api/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpMSIsImlkIjoiNjIxNjE4MTEzODViNmYyM2E0YmNmMjE5IiwiaWF0IjoxNjQ1NjE1MjM5fQ

{
    "content": "Test#30 - added express-async-errors",
    "important": true
}