PUT https://rocky-harbor-47876.herokuapp.com/api/todos/62429d30ee9ccbf1d814f805
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYW5zIiwiaWQiOiI2MjMwNTVhMTYzZDQxYTNlZjdmNTRmNzYiLCJpYXQiOjE2NDg1MzI1MjUsImV4cCI6MTY0ODUzNjEyNX0.DyeZFikZ4QQMMXTCYmV906bwiNqRcctfd6w3sKYJIb4

{
    "content": "FRANS - 29032022 - edit the added",
    "important": true,
    "done": true
}